export const WORKFLOW_STATES = {
  DRAFT: 'draft',
  MISSION_PLANNING: 'mission_planning',
  PATH_DEFINED: 'path_defined',
  AUTONOMY_CONFIGURED: 'autonomy_configured',
  VEHICLE_CONFIGURED: 'vehicle_configured',
  READY_TO_EXECUTE: 'ready_to_execute',
  EXECUTING: 'executing',
  TELEMETRY_REVIEW: 'telemetry_review',
  COMPLETED: 'completed',
  ABORTED: 'aborted',
  ERROR: 'error',
  PAUSED: 'paused',
};

export const MISSION_EVENTS = {
  CREATE_MISSION: 'CREATE_MISSION',
  SET_MISSION_META: 'SET_MISSION_META',
  DEFINE_PATH: 'DEFINE_PATH',
  CONFIGURE_AUTONOMY: 'CONFIGURE_AUTONOMY',
  CONFIGURE_VEHICLE: 'CONFIGURE_VEHICLE',
  VALIDATE_MISSION: 'VALIDATE_MISSION',
  ARM_EXECUTION: 'ARM_EXECUTION',
  START_EXECUTION: 'START_EXECUTION',
  PAUSE_EXECUTION: 'PAUSE_EXECUTION',
  RESUME_EXECUTION: 'RESUME_EXECUTION',
  ABORT_MISSION: 'ABORT_MISSION',
  APPEND_TELEMETRY: 'APPEND_TELEMETRY',
  COMPLETE_MISSION: 'COMPLETE_MISSION',
};

export const TERMINAL_STATES = new Set([
  WORKFLOW_STATES.COMPLETED,
  WORKFLOW_STATES.ABORTED,
]);
